---
# Ansible collection requirements for GitHub-to-Jira Lambda deployment
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: amazon.aws
    version: ">=10.0.0"
  
  - name: community.aws
    version: ">=8.0.0"
